@startuml Expressions
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Expression {
    type: Type
}

class IntLiteral {
    value: int
}

class DoubleLiteral {
    value: double
}

class Variable {
    name: String
    definition: VarDefinition
}

class ArithmeticOperation {
    operator: String
    leftExpression: Expression
    rightExpression: Expression
}

class CharLiteral {
    value: char
}

class Cast {
    variable: Variable
    type: Type
}

class UnaryOperation {
    operator: String
    expression: Expression
}

class LogicOperation {
    operator: String
    leftExpression: Expression
    rightExpression: Expression
}

class Invocation {
    arguments: LIst<Expression>
}

ASTNode <|-- Expression
Expression <|.. IntLiteral
Expression <|.. DoubleLiteral
Expression <|.. CharLiteral
Expression <|.. Variable
Expression <|.. ArithmeticOperation
ArithmeticOperation o-- "2" Expression


@enduml
