@startuml Program
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

class Program

ASTNode <|.. Program
Program <|.. Definition
Definition <|.. VarDefinition
Definition <|.. FunctionDefinition

interface Definition {
    type: Type
}

class VarDefinition {
    name: String
    type: Type
}

class FunctionDefinition {
    name: String
    varDefinitions: VarDefinition
    statements: List<Statement>
    type: FuncType
}

@enduml
