@startuml Types
skinparam style strictuml
skinparam monochrome true

interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Type

ASTNode <|-- Type

class IntType
class DoubleType
class CharType

interface SimpleType

class FuncType {
    params: VarDefinition
    returnType: SimpleType
}

Type <|.. SimpleType
Type <|.. FuncType
SimpleType <|.. IntType
SimpleType <|.. DoubleType
SimpleType <|.. CharType

@enduml
